OrdererOrgs:
  - Name: Orderer
    Domain: plra.gov.pk
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Lahore
    Domain: lahore.plra.gov.pk
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Rawalpindi
    Domain: rawalpindi.plra.gov.pk
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Faisalabad
    Domain: faisalabad.plra.gov.pk
    Template:
      Count: 1
    Users:
      Count: 1
